version: 1.0.{build}

branches:
  only:
    - master

skip_branch_with_pr: true

max_jobs: 1

image: Visual Studio 2017

environment:
  AWS_DEFAULT_REGION: us-west-2
  AWS_ACCESS_KEY_ID:
    secure: IM4hX5vDVy81Mjv0RCbrLcslQtvTUWG50LY8pDr2QT8=
  AWS_SECRET_ACCESS_KEY:
    secure: Sf1Zw0/X4yyWfsDBTffg31ZvqFcXM/LXSyPClYaz4mED0LeAOqwugKgoMbK481vD

init:
  - git config --global core.autocrlf input

shallow_clone: true

#cache:
#  - vcpkg-6

configuration: Release
   
build_script:
#  - ps: $VCPKG = "vcpkg-6"
#  - update-external.bat
#  - ps: $VCPKG = "vcpkg-6"
#  - ps: if(!(Test-Path -Path $VCPKG )){ Invoke-WebRequest "http://intelight.s3.amazonaws.com/vcpkg/$VCPKG.zip" -OutFile $VCPKG".zip"; ls; Expand-Archive -Path ${VCPKG}".zip"; ls }
#  - ps: $wd = $pwd.path -replace "\\", "/"
  - ps: mkdir build
#  - ps: cd build
#  - ps: cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE="$wd/$VCPKG/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-windows-mixed ..
#  - ps: cmake --build . --config Release
   
test: off

#artifacts:
#  - path: build\minigzip\$(configuration)\minigzip.exe
