version: 1.0.{build}

branches:
  only:
    - master

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\maxconnect

shallow_clone: true

platform: x86
configuration: Release

before_build:
  - echo Running cmake...
  - mkdir c:\projects\maxconnect\build
  - cd c:\projects\maxconnect\build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX=%P% ../

build:
  parallel: true
  project: build\maxconnect.sln
