version: 1.0.{build}

branches:
  only:
    - master

max_jobs: 1

image: Visual Studio 2017

environment:
  VCPKG: vcpkg-6

init:
  - git config --global core.autocrlf input

#clone_folder: c:\projects\maxconnect

shallow_clone: true

cache:
  - vcpkg-6

platform: x86
configuration: Release

before_build:
  - echo Prepare vcpkg...
  - ps: echo $Env.VCPKG
  - ps: if(!(Test-Path -Path $Env.VCPKG )){ Invoke-WebRequest "http://intelight.s3.amazonaws.com/vcpkg/$Env.VCPKG.zip" -OutFile $Env.VCPKG.zip; Expand-Archive $Env.VCPKG.zip; ls }
  - echo Running cmake...
  - ps: $wd = $pwd.path -replace "\\", "/"; mkdir build; cd build; cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE="$wd/$Env.VCPKG/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-windows-mixed -DCMAKE_INSTALL_PREFIX=%P%\install ..

build:
  parallel: true
  project: build\maxconnect.sln
